A greene checkout edit 01
swcarpentry/git-novice pull request #758
Opened 2020-09-29 06:16 UTC by agreene71

I've edited the 01-basics.md file to link to updated images for play-changes.svg, versions.svg, and merge.svg (e.g., play-changes_GREENE_CONTRIB_01.svg.  The new images include dash patterns as additional distinguishing features for the colored lines indicating changes to the document in each image.  This was done to improve accessibility, and is based on recommendations from WCAG 2.0.  
Note: I am not sure the images have been linked correctly on the edited .md file.

2020-09-30 01:06 UTC, agreene71 commented on _episodes/01-basics.md
> +![Changes Are Saved Sequentially](https://github.com/agreene71/git-novice/blob/a-greene-checkout-edit-01/fig/play-changes_GREENE_CONTRIB_01.svg)
Fixed image markup.

2021-07-02 21:15 UTC, kekoziar commented
Hi, @agreene71.  I appreciate the change to improve universal access.  Please change the names of the SVGs file to the original (`play-changes`, `merge`, `versions`), and revert the changes in `01-basics.md` to the original code.  Since this lesson is under version control, if someone wants a previous version of `merge.svg`, they only need to go to a previous version of the repository to access it.

2021-07-06 15:19 UTC, agreene71 commented
I am out of town until tomorrow and will take care of this as soon as I can
upon my return.

Thanks,
Andrew

On Fri, Jul 2, 2021 at 5:15 PM K.E. Koziar ***@***.***> wrote:

> Hi, @agreene71 <https://github.com/agreene71>. I appreciate the change to
> improve universal access. Please change the names of the SVGs file to the
> original (play-changes, merge, versions), and revert the changes in
> 01-basics.md to the original code. Since this lesson is under version
> control, if someone wants a previous version of merge.svg, they only need
> to go to a previous version of the repository to access it.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/swcarpentry/git-novice/pull/758#issuecomment-873259842>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACVWVQEJZAVKB4ZBAWXAL73TVYT6JANCNFSM4R5LQJHQ>
> .
>

2021-07-24 13:20 UTC, kekoziar requested changes
Hi, @agreene71.  Are you able to make the file name changes?  If you need assistance, please let me know.  Thanks!

2021-07-26 00:54 UTC, agreene71 commented
Apologies, yes, if assistance could be provided it would be greatly
appreciated.

Thanks,
Andrew

On Sat, Jul 24, 2021 at 9:21 AM K.E. Koziar ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi, @agreene71 <https://github.com/agreene71>. Are you able to make the
> file name changes? If you need assistance, please let me know. Thanks!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/swcarpentry/git-novice/pull/758#pullrequestreview-714234096>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACVWVQDSABNELXMIV4I72XTTZK435ANCNFSM4R5LQJHQ>
> .
>

2021-07-26 15:31 UTC, kekoziar commented
Hi, @agreene71.  I think the easiest way to edit the files for your PR is on the web-interface in GitHub.  If you click on the "Files changed" tab of the PR page, you'll see an ellipsis in the top right for each file listed.  Clicking that will show a menu that includes an "Edit file" option.  When you choose "Edit file" it allows you to change the text in the file *and* the file name.  Let me know if this method works for you.

2021-07-27 01:29 UTC, agreene71 commented
Thank you so much for the guidance.  I think the changes you requested are
done, but please let me know if this is not the case.

Best Regards,
Andrew

On Mon, Jul 26, 2021 at 11:31 AM K.E. Koziar ***@***.***>
wrote:

> Hi, @agreene71 <https://github.com/agreene71>. I think the easiest way to
> edit the files for your PR is on the web-interface in GitHub. If you click
> on the "Files changed" tab of the PR page, you'll see an ellipsis in the
> top right for each file listed. Clicking that will show a menu that
> includes an "Edit file" option. When you choose "Edit file" it allows you
> to change the text in the file *and* the file name. Let me know if this
> method works for you.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/swcarpentry/git-novice/pull/758#issuecomment-886805911>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACVWVQF4YMTQ6BIVPZDZHZLTZV5U7ANCNFSM4R5LQJHQ>
> .
>

2021-07-27 14:33 UTC, kekoziar approved these changes
@agreene71.  Thanks for making the changes.  It looks good.
PR verified and approved.

2021-07-27 14:38 UTC, merged

2021-07-27 15:45 UTC, agreene71 commented
Great, thanks!

Best,
Andrew

On Tue, Jul 27, 2021 at 10:33 AM K.E. Koziar ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> @agreene71 <https://github.com/agreene71>. Thanks for making the changes.
> It looks good.
> PR verified and approved.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/swcarpentry/git-novice/pull/758#pullrequestreview-715997117>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACVWVQGCLJGYM6EE3A52NTLTZ27STANCNFSM4R5LQJHQ>
> .
>