Update to main branch after init
swcarpentry/git-novice pull request #804
Opened 2021-05-17 18:56 UTC by sstevens2

Based on the discussion in issue #761.  Created a PR that switches to the main branch after initializing.

Also added in setup episode suggestion from @srerickson.  @srerickson let me know if you'd prefer I revert that commit so you can get credit in the history.

This does not address all the subsequent times that the branch name appears in the status command.  Looks like there are already a few PRs on that topic #788 and #793

2021-05-17 19:04 UTC, srerickson commented
thanks for offering to revert, but not necessary! thanks for putting this in a PR!

2021-06-30 14:46 UTC, kekoziar requested changes
Can you update your episode 2 file to the most current file?  I merged a different PR for this because it kept the context of "Dracula decides to [...]."  However, I'd like to include some of your content.  Specifically, 

> Source file changes are associated with a "branch." By default, Git will create a branch called `master` when you create a new repository with `git init` (as explained in the next Episode). This term evokes the racist practice of human slavery and the software development community has moved to adopt more inclusive language. 

and, perhaps insert a link to https://github.com/github/renaming?

2021-06-30 21:52 UTC, sstevens2 commented
Hi @ kekoziar. I think I made the changes you suggested.  Additional feedback welcome!

2021-06-30 22:16 UTC, nsoranzo commented on _episodes/03-create.md
> +This might be the default branch depending on your settings and version
```suggestion
This might already be the default branch name depending on your settings and version
```

2021-06-30 22:16 UTC, nsoranzo commented on _episodes/03-create.md
> +of git.
```suggestion
of Git.
```

2021-06-30 22:16 UTC, nsoranzo commented on _episodes/02-setup.md
> +> ## Default Branch Name
I think this part needs to be merged with what has already been added as lines 108-128.

2021-07-01 14:27 UTC, kekoziar commented
Hi, @sstevens2.  Thanks for updating your PR with the current repository.  The intention is to put the first few sentences in the 
"Default Git branch naming" callout that's you pulled in with the update.  I think the link can pair with the phrase "software development community".

Also, as a note, callouts require `{: .callout}` at the end of the section.  You can see the example in the callout I referenced.  

Does this all make sense?

2021-07-05 14:10 UTC, kekoziar commented
verified changes.

2021-07-05 14:12 UTC, merged

2021-07-12 08:28 UTC, michaelberks commented
I'm not sure if this is the best place to leave this comment (there are several open issues re the switch from 'master' to 'main', but I wonder if having set main as the default branch in episode 2: setting up git, we should remove the checkout to main in episode 3?

why:
1. Trying to switch to a branch we're already on isn't normal git practice, and would usually generate an error. The only reason it doesn't throw an error here is because there are no commits yet on main
2. It means the user doesn't know if their global setting has actually worked (because we'll now be on main anyway). Whereas if we miss out the checkout, then when we instruct the user to call 'git status', we can ask them to verify it shows 'main', and if doesn't get them to check their config settings
3. It means we don't have to introduce branch checking out at all, which given we're not covering branches elsewhere in the lesson eases cognitive load

If anyone else agrees, I can put in a PR with suggesting changes (ie dropping the 'git checkout -b main', and adding some text on getting the user to checkout the output from their first 'git status' shows the branch as main)